name: Keep the repo alive
on:
  schedule:
    - cron: "22 12 */3 * *"
  push:
  pull_request:
  fork:
  status:
  issues:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  keep-alive:
    name: Keep the repo alive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        timeout-minutes: 5
      - uses: gautamkrishnar/keepalive-workflow@v1
        timeout-minutes: 5
        with:
          committer_username: ${{ github.repository_owner }}
          committer_email: ${{ github.repository_owner }}@users.noreply.github.com
